version: 5-{build}

branches:
  only:
  - master

skip_non_tags: true

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    Platform: net20
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    Platform: net40
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019  
    Platform: netstandard2.0
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
    Platform: netstandard2.0
  - APPVEYOR_BUILD_WORKER_IMAGE: macos
    Platform: netstandard2.0

build_script:
- cmd: cd build && nuget-build.bat
- sh: dotnet --info && dotnet restore -p:Configuration=Release -p:Platform="Any CPU" -v normal ./src/ && dotnet build -p:Configuration=Release -p:Platform="Any CPU" -v normal ./src/

test_script:
- cmd: IF "%Platform%"=="net20" (nunit3-console -x86 .\src\Pkcs11Interop.Tests\bin\Release\net20\Pkcs11Interop.Tests.dll --result=myresults.xml;format=AppVeyor)
- cmd: IF "%Platform%"=="net40" (nunit3-console .\src\Pkcs11Interop.Tests\bin\Release\net40\Pkcs11Interop.Tests.dll --result=myresults.xml;format=AppVeyor)
- cmd: IF "%Platform%"=="netstandard2.0" (cd .\src\Pkcs11Interop.Tests\ && nuget install Appveyor.TestLogger && cd ..\..)
- cmd: IF "%Platform%"=="netstandard2.0" (dotnet vstest .\src\Pkcs11Interop.Tests\bin\Release\netcoreapp3.1\Pkcs11Interop.Tests.dll --Framework:".NETCoreApp,Version=v3.1" --TestAdapterPath:. --logger:Appveyor)
- sh: cd ./src/Pkcs11Interop.Tests/ && nuget install -Source https://api.nuget.org/v3/index.json Appveyor.TestLogger && cd ../..
- sh: dotnet test -f netcoreapp3.1 --test-adapter-path:. --logger:Appveyor ./src/Pkcs11Interop.Tests/

artifacts:
- path: build/nuget-unsigned/*.nupkg

deploy:
- provider: NuGet
  on:
    platform: netstandard2.0
  api_key:
    secure: KqSVNlWP/wmmLwVWaGLrIx45YXTw3GaTmBG5Lb7F0vUVePl/SVeX3K7e4NxUbnBe
  skip_symbols: true
  artifact: /.*\.nupkg/